package jass.lib;

public final class Card {
    public enum Suit {
        /**
         * All the suits available for the card.
         */
        Clubs, Diamonds, Hearts, Spades;

        @Override
        public String toString() {
            switch (this) {
                case Clubs:
                    return "clubs";
                case Diamonds:
                    return "diamonds";
                case Hearts:
                    return "hearts";
                case Spades:
                    return "spades";
                default:
                    throw new IllegalStateException("Unexpected value: " + this);
            }
        }

        /**
         * @param string The game mode as string.
         *
         * @return Returns the corresponding game mode object.
         */
        public static Suit fromString(final String string) {
            switch (string) {
                case "clubs":
                    return Clubs;
                case "diamonds":
                    return Diamonds;
                case "hearts":
                    return Hearts;
                case "spades":
                    return Spades;
                default:
                    throw new IllegalStateException("Unexpected value: " + string);
            }
        }
    }

    public enum Rank {
        /**
         * All the ranks available for the card.
         */
        Two, Three, Four, Five, Six, Seven, Eight, Nine, Ten, Jack, Queen, King, Ace;

        @Override
        public String toString() {
            String str = "ace";  // Assume we have an ace, then cover all other cases
            // Get ordinal value, which ranges from 0 to 12
            int ordinal = this.ordinal();
            if (ordinal <= 8) {
                str = Integer.toString(ordinal + 2);
            } else if (ordinal == 9) { // Jack
                str = "jack";
            } else if (ordinal == 10) { // Queen
                str = "queen";
            } else if (ordinal == 11) { // King
                str = "king";
            }
            return str;
        }

        /**
         * @param previous Card to compare against.
         *
         * @return Returns true if current object comes after, false otherwise.
         */
        public boolean isNext(final Card previous) {
            int previousOrdinal = previous.rank.ordinal();
            int nextOrdinal = this.ordinal();

            return (previousOrdinal + 1) == nextOrdinal;
        }
    }

    /**
     * The suit.
     */
    private final Suit suit;

    /**
     * The rank.
     */
    private final Rank rank;

    /**
     * @param suit The suit.
     * @param rank The rank.
     */
    public Card(final Suit suit, final Rank rank) {
        this.suit = suit;
        this.rank = rank;
    }

    /**
     * @return Returns the suit.
     */
    public Suit getSuit() {
        return suit;
    }

    /**
     * @return Returns the rank.
     */
    public Rank getRank() {
        return rank;
    }

    @Override
    public String toString() {
        return rank.toString() + "_" + suit.toString();
    }

    /**
     * @param string The string generated by toString().
     *
     * @return Returns a card object according to the string.
     */
    public static Card fromString(final String string) {
        String[] stringSplit = string.split("_");

        String suitString = stringSplit[1];
        Suit suit;
        switch (suitString) {
            case "clubs":
                suit = Suit.Clubs;
                break;
            case "diamonds":
                suit = Suit.Diamonds;
                break;
            case "hearts":
                suit = Suit.Hearts;
                break;
            case "spades":
                suit = Suit.Spades;
                break;
            default:
                throw new IllegalStateException("Unexpected value: " + string);
        }

        String rankString = stringSplit[0];
        Rank rank;
        switch (rankString) {
            case "2":
                rank = Rank.Two;
                break;
            case "3":
                rank = Rank.Three;
                break;
            case "4":
                rank = Rank.Four;
                break;
            case "5":
                rank = Rank.Five;
                break;
            case "6":
                rank = Rank.Six;
                break;
            case "7":
                rank = Rank.Seven;
                break;
            case "8":
                rank = Rank.Eight;
                break;
            case "9":
                rank = Rank.Nine;
                break;
            case "10":
                rank = Rank.Ten;
                break;
            case "jack":
                rank = Rank.Jack;
                break;
            case "queen":
                rank = Rank.Queen;
                break;
            case "king":
                rank = Rank.King;
                break;
            case "ace":
                rank = Rank.Ace;
                break;
            default:
                throw new IllegalStateException("Unexpected value: " + string);
        }

        return new Card(suit, rank);
    }
}
